# Copyright 2025 ETH Zurich and University of Bologna.
# Licensed under the Apache License, Version 2.0, see LICENSE for details.
# SPDX-License-Identifier: Apache-2.0

name: gitlab-ci

on: [ push, pull_request, workflow_dispatch ]

jobs:
  lint-license:
    runs-on: ubuntu-latest
    steps:
    -
      name: Checkout
      uses: actions/checkout@v3
    -
      name: Check license
      uses: pulp-platform/pulp-actions/lint-license@v2
      with:
        license: |
          Copyright (\d{4}(-\d{4})?\s)?(ETH Zurich and University of Bologna|lowRISC contributors).
          (Solderpad Hardware License, Version 0.51|Licensed under the Apache License, Version 2.0), see LICENSE for details.
          SPDX-License-Identifier: (SHL-0.51|Apache-2.0)
        # Exclude generated headers (no license checker support for optional lines)
        exclude_paths: |
          software/*
          util/*
          docs/*
          install/*
          config/*
          hardware/tb/dpi/*
          Bender.lock
          .gitignore

  lint-sv:
    runs-on: ubuntu-latest
    steps:
    -
      name: Checkout
      uses: actions/checkout@v3
    -
      name: Run Verible
      uses: chipsalliance/verible-linter-action@main
      with:
        paths: hardware
        github_token: ${{ secrets.GITHUB_TOKEN }}
        fail_on_error: false
        reviewdog_reporter: github-check

  gitlab-ci:
    runs-on: ubuntu-latest
    steps:
      - name: Check Gitlab CI
        uses: pulp-platform/pulp-actions/gitlab-ci@v2.4.1 
        if: github.repository == 'pulp-platform/ManyRVData' && (github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name == github.repository)
        with:
          domain: iis-git.ee.ethz.ch
          repo: github-mirror/ManyRVData
          token: ${{ secrets.GITLAB_TOKEN }}
