name: gitlab-ci

on: [ push, pull_request, workflow_dispatch ]

jobs:
  gitlab-ci:
    runs-on: ubuntu-latest
    steps:
      - name: Check Gitlab CI
        uses: pulp-platform/pulp-actions/gitlab-ci@v2.4.1 
        if: github.repository == 'pulp-platform/ManyRVData' && (github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name == github.repository)
        with:
          domain: iis-git.ee.ethz.ch
          repo: github-mirror/ManyRVData
          token: ${{ secrets.GITLAB_TOKEN }}